// Generated from '2024 애프터버너 브랜드별 로스팅기 결합실적_241031.pdf' — do not edit by hand.
// Source record count: 155 · 17 brands · 2024.10.31 compilation.

export type AfterburnerCombo = {
  company: string;
  roastKg: string;
  burnerKg: string;
  location: string;
  brand: string;
};

export const AFTERBURNER_BRAND_COMBOS: AfterburnerCombo[] = [
  { company: "씨네스타커피", roastKg: "15", burnerKg: "15", location: "서울 용산구", brand: "PROBAT" },
  { company: "이디야커피", roastKg: "5", burnerKg: "10", location: "서울 강남구", brand: "PROBAT" },
  { company: "커피포션", roastKg: "5", burnerKg: "5", location: "광주 서구", brand: "PROBAT" },
  { company: "올넥스트", roastKg: "5", burnerKg: "10", location: "서울 종로구", brand: "PROBAT" },
  { company: "커피둘세", roastKg: "5", burnerKg: "5", location: "서울 영등포구", brand: "PROBAT" },
  { company: "라붐팩토리", roastKg: "60", burnerKg: "60", location: "경기 의왕시", brand: "PROBAT" },
  { company: "터치아프리카", roastKg: "5", burnerKg: "5", location: "경기 고양시", brand: "PROBAT" },
  { company: "체리빈커피", roastKg: "10", burnerKg: "15", location: "대구 남구", brand: "PROBAT" },
  { company: "SHIL LONG LIOU (Tiami)", roastKg: "10", burnerKg: "10", location: "TAIWAN", brand: "PROBAT" },
  { company: "커피리브레", roastKg: "120", burnerKg: "100", location: "경기 파주시", brand: "PROBAT" },
  { company: "커피리브레", roastKg: "60", burnerKg: "50", location: "경기 파주시", brand: "PROBAT" },
  { company: "디스커버리 로스터스", roastKg: "20", burnerKg: "20", location: "대구 수성구", brand: "PROBAT" },
  { company: "도리아노", roastKg: "3", burnerKg: "3", location: "전라남도 무안군", brand: "PROBAT" },
  { company: "CBSC", roastKg: "5", burnerKg: "5", location: "경기 고양시", brand: "PROBAT" },
  { company: "바른커피", roastKg: "5", burnerKg: "5", location: "서울 용산구", brand: "PROBAT" },
  { company: "리마커블커피", roastKg: "5", burnerKg: "5", location: "경기 오산시", brand: "PROBAT" },
  { company: "오월의 숲", roastKg: "30", burnerKg: "30", location: "충청남도 천안시", brand: "PROBAT" },
  { company: "엠커피", roastKg: "5", burnerKg: "5", location: "경기 남양주시", brand: "PROBAT" },
  { company: "커피러브스토리", roastKg: "5", burnerKg: "5", location: "대전 서구", brand: "PROBAT" },
  { company: "커피맵아카데미학원", roastKg: "5", burnerKg: "5", location: "경상남도 창원시", brand: "PROBAT" },
  { company: "㈜커피뚜깡", roastKg: "15", burnerKg: "15", location: "서울 마포구", brand: "PROBAT" },
  { company: "터치아프리카", roastKg: "5", burnerKg: "10", location: "경기 고양시", brand: "PROBAT" },
  { company: "EXPORT CHINA", roastKg: "12", burnerKg: "15", location: "CHINA", brand: "PROBAT" },
  { company: "커피맛을 조금 아는 남자", roastKg: "12", burnerKg: "15", location: "대구 수성구", brand: "PROBAT" },
  { company: "Blue-mountain-café", roastKg: "12", burnerKg: "15", location: "CHINA", brand: "PROBAT" },
  { company: "TIAMO TAIWAN", roastKg: "5", burnerKg: "10", location: "TAIWAN", brand: "PROBAT" },
  { company: "이런커피", roastKg: "60", burnerKg: "60", location: "대구 수성구", brand: "PROBAT" },
  { company: "춤추는북카페", roastKg: "5", burnerKg: "5", location: "충청북도 청주시", brand: "FUJI ROYAL" },
  { company: "엠제이통상", roastKg: "10", burnerKg: "15", location: "경기 과천시", brand: "FUJI ROYAL" },
  { company: "가배두림", roastKg: "10", burnerKg: "15", location: "서울 금천구", brand: "FUJI ROYAL" },
  { company: "더원커피", roastKg: "5", burnerKg: "5", location: "경상남도 창원시", brand: "FUJI ROYAL" },
  { company: "8STREET", roastKg: "5", burnerKg: "15", location: "서울 동대문구", brand: "FUJI ROYAL" },
  { company: "커피산책", roastKg: "5", burnerKg: "5", location: "서울 중구", brand: "FUJI ROYAL" },
  { company: "교보문고(커피자우랩)", roastKg: "10", burnerKg: "10", location: "서울 마포구", brand: "FUJI ROYAL" },
  { company: "FUJIROYAL CHINA", roastKg: "?", burnerKg: "?", location: "CHINA", brand: "FUJI ROYAL" },
  { company: "FUJIROYAL CHINA", roastKg: "?", burnerKg: "?", location: "CHINA", brand: "FUJI ROYAL" },
  { company: "FUJIROYAL CHINA", roastKg: "?", burnerKg: "?", location: "CHINA", brand: "FUJI ROYAL" },
  { company: "FUJIROYAL CHINA", roastKg: "?", burnerKg: "?", location: "CHINA", brand: "FUJI ROYAL" },
  { company: "노아스로스팅", roastKg: "?", burnerKg: "?", location: "경기 고양시", brand: "FUJI ROYAL" },
  { company: "파머스테이블", roastKg: "6", burnerKg: "15", location: "경기 양주시", brand: "GIESEN" },
  { company: "카페 드 앙떼띠", roastKg: "5", burnerKg: "5", location: "서울 서초구", brand: "GIESEN" },
  { company: "쿠파렌탈하우스", roastKg: "15", burnerKg: "15", location: "경기 광주시", brand: "GIESEN" },
  { company: "카페메이븐", roastKg: "6", burnerKg: "5", location: "서울 마포구", brand: "GIESEN" },
  { company: "#52로스터스랩", roastKg: "6", burnerKg: "10", location: "서울 중구", brand: "GIESEN" },
  { company: "펠리시타 로스터리㈜", roastKg: "15", burnerKg: "15", location: "경기 파주시", brand: "GIESEN" },
  { company: "펠리시타 로스터리㈜", roastKg: "60", burnerKg: "60", location: "경기 파주시", brand: "GIESEN" },
  { company: "쿼츠커피", roastKg: "6", burnerKg: "10", location: "서울 성북구", brand: "GIESEN" },
  { company: "커피맛을 조금아는 남자", roastKg: "10", burnerKg: "10", location: "대구 수성구", brand: "GIESEN" },
  { company: "킹덤플랜트", roastKg: "6", burnerKg: "10", location: "경상북도 안동시", brand: "GIESEN" },
  { company: "이런커피", roastKg: "20", burnerKg: "20", location: "대구 동구", brand: "BUHLER" },
  { company: "커피디셈버", roastKg: "20", burnerKg: "20", location: "경기 안양시", brand: "BUHLER" },
  { company: "커피하우스", roastKg: "20", burnerKg: "20", location: "광주 광산구", brand: "BUHLER" },
  { company: "커피신화", roastKg: "20", burnerKg: "15", location: "전라북도 군산시", brand: "BUHLER" },
  { company: "예담커피", roastKg: "20", burnerKg: "15", location: "광주 북구", brand: "BUHLER" },
  { company: "이런커피", roastKg: "20", burnerKg: "20", location: "대구 수성구", brand: "BUHLER" },
  { company: "㈜양치기소년들", roastKg: "20", burnerKg: "20", location: "경기 시흥시", brand: "BUHLER" },
  { company: "라이프커피컴퍼니", roastKg: "1.8", burnerKg: "3", location: "서울 서대문구", brand: "EASYSTER" },
  { company: "업.사이드", roastKg: "8", burnerKg: "5", location: "서울 용산구", brand: "EASYSTER" },
  { company: "커피농장의 하루", roastKg: "7", burnerKg: "5", location: "서울 광진구", brand: "EASYSTER" },
  { company: "윈스컴퍼니", roastKg: "4", burnerKg: "3", location: "서울 강남구", brand: "EASYSTER" },
  { company: "블랙그라운드", roastKg: "8", burnerKg: "5", location: "서울 영등포구", brand: "EASYSTER" },
  { company: "소호커피팩토리", roastKg: "4", burnerKg: "3", location: "서울 송파구", brand: "EASYSTER" },
  { company: "레피스리보부상", roastKg: "1.8", burnerKg: "3", location: "전라북도 군산시", brand: "EASYSTER" },
  { company: "SHEEP COFFEE", roastKg: "4", burnerKg: "5", location: "부산 부산진구", brand: "EASYSTER" },
  { company: "커퍼런트", roastKg: "4", burnerKg: "5", location: "인천 연수구", brand: "EASYSTER" },
  { company: "비비드컴퍼니", roastKg: "4", burnerKg: "5", location: "서울 강북구", brand: "EASYSTER" },
  { company: "카페진정성", roastKg: "8", burnerKg: "5", location: "경기 김포시", brand: "EASYSTER" },
  { company: "수상한 원두", roastKg: "4", burnerKg: "5", location: "경기 부천시", brand: "EASYSTER" },
  { company: "카페 남산아래", roastKg: "8", burnerKg: "5", location: "서울 중구", brand: "EASYSTER" },
  { company: "크리처커피컴퍼니", roastKg: "8", burnerKg: "5", location: "대전 중구", brand: "EASYSTER" },
  { company: "크리처커피컴퍼니", roastKg: "8", burnerKg: "5", location: "경상북도 포항시", brand: "EASYSTER" },
  { company: "크루빈컴퍼니", roastKg: "8", burnerKg: "5", location: "경상남도 창원시", brand: "EASYSTER" },
  { company: "I’M 1L", roastKg: "8", burnerKg: "5", location: "대전 중구", brand: "EASYSTER" },
  { company: "SORIM COFFEE", roastKg: "4", burnerKg: "5", location: "서울 마포구", brand: "EASYSTER" },
  { company: "COFFEE WRITE", roastKg: "8", burnerKg: "5", location: "서울 강남구", brand: "EASYSTER" },
  { company: "배트콩커피", roastKg: "8", burnerKg: "5", location: "서울 동대문구", brand: "EASYSTER" },
  { company: "스웨르떼", roastKg: "8", burnerKg: "5", location: "경기 수원시", brand: "EASYSTER" },
  { company: "커피그래", roastKg: "8", burnerKg: "5", location: "서울 중구", brand: "EASYSTER" },
  { company: "리퍼블릭오브블루", roastKg: "4", burnerKg: "5", location: "서울 서초구", brand: "EASYSTER" },
  { company: "TREASURES", roastKg: "4", burnerKg: "5", location: "부산 진구", brand: "EASYSTER" },
  { company: "여수", roastKg: "7", burnerKg: "5", location: "전라남도 여수시", brand: "EASYSTER" },
  { company: "칠복상회", roastKg: "7", burnerKg: "5", location: "서울 강북구", brand: "EASYSTER" },
  { company: "FILL OUT", roastKg: "7", burnerKg: "5", location: "경기 성남시", brand: "EASYSTER" },
  { company: "원불교", roastKg: "7", burnerKg: "5", location: "서울 동작구", brand: "EASYSTER" },
  { company: "육각커피", roastKg: "4", burnerKg: "5", location: "광주 남구", brand: "EASYSTER" },
  { company: "커피스니퍼", roastKg: "4", burnerKg: "5", location: "서울 중구", brand: "EASYSTER" },
  { company: "아르보르", roastKg: "15", burnerKg: "15", location: "경기 이천시", brand: "EASYSTER" },
  { company: "디터틀", roastKg: "1.8", burnerKg: "3", location: "서울 종로구", brand: "EASYSTER" },
  { company: "프로듀스썸띵굿", roastKg: "8", burnerKg: "10", location: "부산 수영구", brand: "EASYSTER" },
  { company: "씨에프씨", roastKg: "8", burnerKg: "5", location: "부산 금정구", brand: "EASYSTER" },
  { company: "JS패밀리", roastKg: "8", burnerKg: "10", location: "경기 평택시", brand: "EASYSTER" },
  { company: "뉴스커피", roastKg: "15", burnerKg: "15", location: "부산 부산진구", brand: "EASYSTER" },
  { company: "미루꾸커피", roastKg: "8", burnerKg: "10", location: "경기 고양시", brand: "EASYSTER" },
  { company: "㈜조세통람", roastKg: "1.8", burnerKg: "5", location: "서울 중구", brand: "EASYSTER" },
  { company: "아피커피", roastKg: "30", burnerKg: "30", location: "경기 남양주시", brand: "EASYSTER" },
  { company: "㈜베노빅센", roastKg: "15", burnerKg: "15", location: "서울 광진구", brand: "OZTURK" },
  { company: "커피 더 맨", roastKg: "10", burnerKg: "10", location: "서울 용산구", brand: "OZTURK" },
  { company: "그린빈에스텍", roastKg: "15", burnerKg: "15", location: "서울 송파구", brand: "OZTURK" },
  { company: "카페클락", roastKg: "10", burnerKg: "10", location: "경기 평택시", brand: "OZTURK" },
  { company: "리얼빈", roastKg: "5", burnerKg: "5", location: "서울 강남구", brand: "OZTURK" },
  { company: "그레이커피로스터스", roastKg: "15", burnerKg: "15", location: "서울 금천구", brand: "OZTURK" },
  { company: "커피내음", roastKg: "10", burnerKg: "10", location: "서울 양천구", brand: "OZTURK" },
  { company: "비엠커피컴퍼니", roastKg: "15", burnerKg: "15", location: "서울 성동구", brand: "PROASTER" },
  { company: "로스팅포인트", roastKg: "5", burnerKg: "10", location: "서울 송파구", brand: "PROASTER" },
  { company: "로스팅팩토리", roastKg: "10", burnerKg: "10", location: "서울 서대문구", brand: "PROASTER" },
  { company: "크림탑커피", roastKg: "5", burnerKg: "5", location: "서울 성북구", brand: "PROASTER" },
  { company: "파라디소커피", roastKg: "5", burnerKg: "5", location: "경기 성남시", brand: "PROASTER" },
  { company: "커피플랜트", roastKg: "30", burnerKg: "30", location: "서울 강남구", brand: "PROASTER" },
  { company: "올댓커피 (넥스트씨앤씨)", roastKg: "6", burnerKg: "10", location: "경기 광명시", brand: "PROASTER" },
  { company: "대동대학교 바리스타학과", roastKg: "15", burnerKg: "15", location: "부산 금정구", brand: "PROASTER" },
  { company: "콩가게", roastKg: "5", burnerKg: "5", location: "경기 안양시", brand: "PROASTER" },
  { company: "카페무띠", roastKg: "15", burnerKg: "10", location: "서울 강동구", brand: "PROASTER" },
  { company: "미소랑커피시스템", roastKg: "5", burnerKg: "5", location: "경기 구리시", brand: "PROASTER" },
  { company: "나는커피", roastKg: "6", burnerKg: "10", location: "부산 수영구", brand: "PROASTER" },
  { company: "넥스트씨앤씨(올댓커피)", roastKg: "30", burnerKg: "30", location: "서울 금천구", brand: "PROASTER" },
  { company: "초록창고", roastKg: "5", burnerKg: "5", location: "서울 서초구", brand: "PROASTER" },
  { company: "카페지기", roastKg: "10", burnerKg: "10", location: "서울 중랑구", brand: "PROASTER" },
  { company: "태양커피", roastKg: "3", burnerKg: "5", location: "서울 서초구", brand: "PROASTER" },
  { company: "피피커피", roastKg: "1", burnerKg: "5", location: "서울 마포구", brand: "PROASTER" },
  { company: "라벨커피", roastKg: "7", burnerKg: "10", location: "서울 강남구", brand: "BEANMASTER" },
  { company: "기리다커피", roastKg: "7", burnerKg: "10", location: "인천 남동구", brand: "BEANMASTER" },
  { company: "5스타커피", roastKg: "7", burnerKg: "10", location: "서울 중랑구", brand: "BEANMASTER" },
  { company: "일공일이커피", roastKg: "4", burnerKg: "5", location: "서울 성동구", brand: "BEANMASTER" },
  { company: "코피발리", roastKg: "7", burnerKg: "10", location: "서울 종로구", brand: "BEANMASTER" },
  { company: "위드빈커피", roastKg: "4", burnerKg: "5", location: "서울 송파구", brand: "BEANMASTER" },
  { company: "조상일 커피", roastKg: "6", burnerKg: "5", location: "경기 군포시", brand: "BEANMASTER" },
  { company: "씨엔더블유", roastKg: "7", burnerKg: "5", location: "서울 용산구", brand: "BEANMASTER" },
  { company: "제이엔커피디자인", roastKg: "7", burnerKg: "5", location: "인천 서구", brand: "BEANMASTER" },
  { company: "몽중화", roastKg: "7", burnerKg: "5", location: "서울 마포구", brand: "BEANMASTER" },
  { company: "그라노드커피", roastKg: "7", burnerKg: "5", location: "경기 평택시", brand: "BEANMASTER" },
  { company: "제이윤커피컴퍼니", roastKg: "5", burnerKg: "5", location: "경기 고양시", brand: "BEANMASTER" },
  { company: "엘미가", roastKg: "3", burnerKg: "3", location: "서울 강남구", brand: "HASGARANTI" },
  { company: "더콰이엍커피", roastKg: "5", burnerKg: "5", location: "서울 마포구", brand: "HASGARANTI" },
  { company: "롱블랙", roastKg: "5", burnerKg: "5", location: "서울 성동구", brand: "HASGARANTI" },
  { company: "바른커피", roastKg: "5", burnerKg: "5", location: "서울 동대문구", brand: "HASGARANTI" },
  { company: "마이티커피", roastKg: "5", burnerKg: "5", location: "제주 제주시", brand: "HASGARANTI" },
  { company: "카브로시아", roastKg: "10", burnerKg: "5", location: "경기 고양시", brand: "TYPHOON" },
  { company: "신화마스터피스", roastKg: "20", burnerKg: "40", location: "광주 서구", brand: "TORISTER" },
  { company: "CNC커피", roastKg: "15", burnerKg: "15", location: "전라북도 익산시", brand: "TORISTER" },
  { company: "CNC커피", roastKg: "30", burnerKg: "30", location: "전라북도 익산시", brand: "TORISTER" },
  { company: "히즈라네고양이카페", roastKg: "5", burnerKg: "5", location: "서울 구로구", brand: "COFFEEBOB" },
  { company: "커피지만", roastKg: "10", burnerKg: "10", location: "경기 남양주시", brand: "COFFEEBOB" },
  { company: "83LAB", roastKg: "1", burnerKg: "5", location: "경기 남양주시", brand: "TOPER" },
  { company: "로스팅코리아", roastKg: "30", burnerKg: "30", location: "경상남도 양산시", brand: "RIO" },
  { company: "리사르커피", roastKg: "10", burnerKg: "10", location: "서울 중구", brand: "SANFRANCISCAN" },
  { company: "베를린크란츠", roastKg: "5", burnerKg: "10", location: "서울 강남구", brand: "DIEDRICH" },
  { company: "달출판사", roastKg: "5", burnerKg: "5", location: "경기 파주시", brand: "DIEDRICH" },
  { company: "PIT COFFEE", roastKg: "10", burnerKg: "15", location: "서울 마포구", brand: "DIEDRICH" },
  { company: "카페비마이프렌드", roastKg: "35", burnerKg: "30", location: "충청북도 태안군", brand: "DIEDRICH" },
  { company: "마에스터커피", roastKg: "15", burnerKg: "15", location: "서울 강서구", brand: "JOPER" },
  { company: "C.M.P COFFEE", roastKg: "3", burnerKg: "5", location: "서울 은평구", brand: "JOPER" },
  { company: "오월의 숲", roastKg: "7", burnerKg: "10", location: "충청남도 천안시", brand: "STRONGHOLD" },
  { company: "오월의 숲", roastKg: "30", burnerKg: "30", location: "충청남도 천안시", brand: "STRONGHOLD" },
  { company: "더 나우커피", roastKg: "3", burnerKg: "5", location: "서울 양천구", brand: "JOPER" },
  { company: "넬쿠오레델카페", roastKg: "5", burnerKg: "5", location: "서울 송파구", brand: "TOPER" },
];
