const S3_PRODUCT = "https://chiro-web.s3.ap-northeast-2.amazonaws.com/fa/AFTERBUNNER/products";

// ── AFTERBURNER MODELS ──
export const AFTERBURNER_MODELS = [
  {
    id: "nkic-5k",
    name: "NKIC-5K",
    capacity: "5kg",
    target: "Small Roastery",
    targetKr: "소형 로스터리",
    size: "435 × 545 × 1,310mm",
    burner: "Surface Combustion Metal Burner",
    burnerKr: "표면 연소 메탈 버너",
    controller: "Digital",
    image: `${S3_PRODUCT}/ab-5k-1.png`,
    gallery: [`${S3_PRODUCT}/ab-5k-1.png`, `${S3_PRODUCT}/ab-5k-2.png`],
  },
  {
    id: "nkic-10k",
    name: "NKIC-10K",
    capacity: "10kg",
    target: "Medium Café",
    targetKr: "중형 카페",
    size: "545 × 645 × 1,700mm",
    burner: "Dual-Stage Duct Burner",
    burnerKr: "2단 덕트 버너",
    controller: "Digital",
    image: `${S3_PRODUCT}/ab-10k-1.jpg`,
    gallery: [`${S3_PRODUCT}/ab-10k-1.jpg`, `${S3_PRODUCT}/ab-10k-2.jpg`],
  },
  {
    id: "nkic-15k",
    name: "NKIC-15K",
    capacity: "15kg",
    target: "Large Roastery",
    targetKr: "대형 로스터리",
    size: "545 × 655 × 1,795mm",
    burner: "Dual-Stage Duct Burner",
    burnerKr: "2단 덕트 버너",
    controller: "Touch Screen",
    image: `${S3_PRODUCT}/ab-15k-2.png`,
    gallery: [`${S3_PRODUCT}/ab-15k-1.png`, `${S3_PRODUCT}/ab-15k-2.png`],
  },
  {
    id: "nkic-30k",
    name: "NKIC-30K",
    capacity: "30kg",
    target: "Industrial",
    targetKr: "산업용",
    size: "645 × 655 × 1,895mm",
    burner: "Dual-Stage Duct Burner",
    burnerKr: "2단 덕트 버너",
    controller: "Proportional",
    image: `${S3_PRODUCT}/ab-30k-1.png`,
    gallery: [`${S3_PRODUCT}/ab-30k-1.png`],
  },
  {
    id: "nkic-60k",
    name: "NKIC-60K",
    capacity: "60kg",
    target: "Large Facility",
    targetKr: "대형 시설",
    size: "645 × 750 × 2,190mm",
    burner: "Dual-Stage Duct Burner",
    burnerKr: "2단 덕트 버너",
    controller: "Proportional",
    image: `${S3_PRODUCT}/afterburner-main.png`,
    gallery: [`${S3_PRODUCT}/afterburner-main.png`],
  },
  {
    id: "nkic-120k",
    name: "NKIC-120K",
    capacity: "120kg",
    target: "Large Industrial",
    targetKr: "대형 산업용",
    size: "800 × 900 × 2,500mm",
    burner: "Dual-Stage Duct Burner",
    burnerKr: "2단 덕트 버너",
    controller: "Proportional",
    image: `${S3_PRODUCT}/afterburner-metal.png`,
    gallery: [`${S3_PRODUCT}/afterburner-metal.png`],
  },
];

export const AFTERBURNER_COMMON_SPECS = {
  heatSource: "LNG / LPG",
  combustionTemp: "200°C ~ 1,000°C",
  removalRate: "99.2%",
  power: "220V single-phase 50/60Hz",
  gasSaving: "30%",
};

export const COMPATIBLE_ROASTERS = [
  "PROBAT", "GIESEN", "LORING", "FUJI ROYAL", "PROASTER",
  "OZTURK", "DIEDRICH", "TOPER", "BUHLER", "JOPER",
];

// ── ROASTER MODELS ──
export const ROASTER_BASE_MODELS = [
  {
    id: "base-05",
    name: "BASE 0.5",
    capacity: "0.5kg",
    target: "Sample / Education",
    targetKr: "샘플 / 교육용",
    size: "56 × 89 × 92cm",
    weight: "65kg",
    power: "0.72kW",
    burner: "5kW",
    controller: "Manual / Digital Speed",
    image: `${S3_PRODUCT}/roaster-05kg-1.jpg`,
    gallery: [`${S3_PRODUCT}/roaster-05kg-1.jpg`, `${S3_PRODUCT}/roaster-05kg-2.jpg`, `${S3_PRODUCT}/roaster-05kg-3.jpg`, `${S3_PRODUCT}/roaster-05kg-4.jpg`],
  },
  {
    id: "base-1.5",
    name: "BASE 1.5",
    capacity: "1.5kg",
    target: "Small Café",
    targetKr: "소형 카페",
    size: "87 × 115 × 127cm",
    weight: "155kg",
    power: "1.84kW",
    burner: "10kW",
    controller: "PLC (optional)",
    image: `${S3_PRODUCT}/roaster-1.5kg-main.jpg`,
    gallery: [`${S3_PRODUCT}/roaster-1_5kg-1.jpg`, `${S3_PRODUCT}/roaster-1_5kg-2.jpg`, `${S3_PRODUCT}/roaster-1_5kg-3.png`, `${S3_PRODUCT}/roaster-1_5kg-4.png`, `${S3_PRODUCT}/roaster-1_5kg-5.png`],
  },
  {
    id: "base-3",
    name: "BASE 3",
    capacity: "3kg",
    target: "Roastery Café",
    targetKr: "로스터리 카페",
    size: "87 × 135 × 150cm",
    weight: "270kg",
    power: "1.24kW",
    burner: "27.5kW",
    controller: "PLC (optional)",
    image: `${S3_PRODUCT}/roaster-3kg-1.jpg`,
    gallery: [`${S3_PRODUCT}/roaster-3kg-1.jpg`, `${S3_PRODUCT}/roaster-3kg-2.jpg`, `${S3_PRODUCT}/roaster-3kg-3.png`, `${S3_PRODUCT}/roaster-3kg-4.png`, `${S3_PRODUCT}/roaster-3kg-5.png`],
  },
  {
    id: "base-5",
    name: "BASE 5",
    capacity: "5kg",
    target: "Medium Roastery",
    targetKr: "중형 로스터리",
    size: "90 × 155 × 165cm",
    weight: "330kg",
    power: "1.84kW",
    burner: "35kW",
    controller: "Software & Touchscreen",
    image: `${S3_PRODUCT}/roaster-5kg-1.jpg`,
    gallery: [`${S3_PRODUCT}/roaster-5kg-1.jpg`, `${S3_PRODUCT}/roaster-5kg-2.jpg`, `${S3_PRODUCT}/roaster-5kg-3.png`, `${S3_PRODUCT}/roaster-5kg-4.png`, `${S3_PRODUCT}/roaster-5kg-5.png`],
  },
  {
    id: "base-10",
    name: "BASE 10",
    capacity: "10kg",
    target: "Large Roastery",
    targetKr: "대형 로스터리",
    size: "107 × 195 × 190cm",
    weight: "480kg",
    power: "2.24kW",
    burner: "55kW",
    controller: "Full Auto / Touchscreen",
    image: `${S3_PRODUCT}/roaster-10kg-main.jpg`,
    gallery: [`${S3_PRODUCT}/roaster-10kg-1.jpg`, `${S3_PRODUCT}/roaster-10kg-2.jpg`, `${S3_PRODUCT}/roaster-10kg-3.png`, `${S3_PRODUCT}/roaster-10kg-4.png`],
  },
  {
    id: "base-15",
    name: "BASE 15",
    capacity: "15kg",
    target: "Large Factory",
    targetKr: "대형 공장",
    size: "107 × 200 × 195cm",
    weight: "530kg",
    power: "2.24kW",
    burner: "55kW",
    controller: "Software & Touchscreen",
    image: `${S3_PRODUCT}/roaster-15kg-1.png`,
    gallery: [`${S3_PRODUCT}/roaster-15kg-1.png`, `${S3_PRODUCT}/roaster-15kg-2.png`, `${S3_PRODUCT}/roaster-15kg-3.png`, `${S3_PRODUCT}/roaster-15kg-4.jpg`],
  },
  {
    id: "base-20",
    name: "BASE 20",
    capacity: "20kg",
    target: "Industrial",
    targetKr: "산업용",
    size: "115 × 210 × 205cm",
    weight: "670kg",
    power: "2.24kW",
    burner: "35kW",
    controller: "Software & Touchscreen",
    image: `${S3_PRODUCT}/roaster-20kg-1.jpg`,
    gallery: [`${S3_PRODUCT}/roaster-20kg-1.jpg`, `${S3_PRODUCT}/roaster-20kg-2.jpg`, `${S3_PRODUCT}/roaster-20kg-3.jpg`, `${S3_PRODUCT}/roaster-20kg-4.jpg`],
  },
];

export const ROASTER_SUPREME_IMAGE = `${S3_PRODUCT}/roaster-supreme-1.png`;
export const ROASTER_SUPREME_GALLERY = [
  `${S3_PRODUCT}/roaster-supreme-1.png`,
  `${S3_PRODUCT}/roaster-supreme-2.jpg`,
  `${S3_PRODUCT}/roaster-supreme-3.jpg`,
  `${S3_PRODUCT}/roaster-supreme-4.jpg`,
  `${S3_PRODUCT}/roaster-supreme-5.png`,
];

export const HERO_IMAGES = {
  afterburner: `${S3_PRODUCT}/hero-afterburner.png`,
  roaster: `${S3_PRODUCT}/hero-roaster.png`,
  nutbutter: `${S3_PRODUCT}/hero-nutbutter.png`,
};
