const S3_PRODUCT = "https://chiro-web.s3.ap-northeast-2.amazonaws.com/fa/AFTERBUNNER/products";

// ── AFTERBURNER MODELS (image map synced with chiroweb/nbpcofe reference) ──
export const AFTERBURNER_MODELS = [
  {
    id: "nkic-5k",
    name: "NKIC-5K",
    capacity: "5kg",
    target: "Small Roastery",
    targetKr: "중소형 로스터리",
    size: "435 × 545 × 1,310mm",
    burner: "Surface Combustion Metal Burner",
    burnerKr: "표면연소 고효율 메탈버너",
    controller: "Digital",
    connector: "도시가스 (13A)",
    image: `${S3_PRODUCT}/ab-1k-1.png`,
    gallery: [`${S3_PRODUCT}/ab-1k-1.png`],
  },
  {
    id: "nkic-10k",
    name: "NKIC-10K",
    capacity: "10kg",
    target: "Medium Café",
    targetKr: "중형 로스터리 카페",
    size: "545 × 645 × 1,700mm",
    burner: "Dual-Stage Duct Burner",
    burnerKr: "이단연소 고효율 덕트버너",
    controller: "Digital",
    connector: "LPG / 도시가스 (13A)",
    image: `${S3_PRODUCT}/afterburner-white.png`,
    gallery: [`${S3_PRODUCT}/afterburner-white.png`, `${S3_PRODUCT}/afterburner-metal.png`],
  },
  {
    id: "nkic-15k",
    name: "NKIC-15K",
    capacity: "15kg",
    target: "Large Roastery",
    targetKr: "대형 로스터리",
    size: "545 × 655 × 1,795mm",
    burner: "Dual-Stage Duct Burner",
    burnerKr: "이단연소 고효율 덕트버너",
    controller: "Touch Screen",
    connector: "LPG / 도시가스 (13A)",
    image: `${S3_PRODUCT}/ab-15k-2.png`,
    gallery: [`${S3_PRODUCT}/ab-15k-2.png`, `${S3_PRODUCT}/afterburner-black.png`],
  },
  {
    id: "nkic-30k",
    name: "NKIC-30K",
    capacity: "30kg",
    target: "Industrial",
    targetKr: "산업용 대량 로스팅",
    size: "645 × 655 × 1,895mm",
    burner: "Dual-Stage Duct Burner",
    burnerKr: "이단연소 고효율 덕트버너",
    controller: "Proportional",
    connector: "LPG / 도시가스 (13A)",
    image: `${S3_PRODUCT}/ab-10k-1.jpg`,
    gallery: [`${S3_PRODUCT}/ab-10k-1.jpg`, `${S3_PRODUCT}/ab-10k-2.jpg`],
  },
  {
    id: "nkic-60k",
    name: "NKIC-60K",
    capacity: "60kg",
    target: "Large Facility",
    targetKr: "대규모 산업 시설",
    size: "645 × 750 × 2,190mm",
    burner: "Dual-Stage Duct Burner",
    burnerKr: "이단연소 고효율 덕트버너",
    controller: "Proportional",
    connector: "LPG / 도시가스 (13A)",
    image: `${S3_PRODUCT}/ab-30k-1.png`,
    gallery: [`${S3_PRODUCT}/ab-30k-1.png`],
  },
  {
    id: "nkic-120k",
    name: "NKIC-120K",
    capacity: "120kg",
    target: "Large Industrial",
    targetKr: "대형 산업 플랜트",
    size: "800 × 900 × 2,500mm",
    burner: "Dual-Stage Duct Burner",
    burnerKr: "이단연소 고효율 덕트버너",
    controller: "Proportional",
    connector: "LPG / 도시가스 (13A)",
    image: `${S3_PRODUCT}/afterburner-main.png`,
    gallery: [`${S3_PRODUCT}/afterburner-main.png`],
  },
];

export const AFTERBURNER_COMMON_SPECS = {
  heatSource: "LNG / LPG",
  combustionTemp: "200°C ~ 1,000°C",
  removalRate: "99.2%",
  power: "220V single-phase 50/60Hz",
  gasSaving: "30%",
};

export const COMPATIBLE_ROASTERS = [
  "PROBAT", "GIESEN", "LORING", "FUJI ROYAL", "PROASTER",
  "OZTURK", "DIEDRICH", "TOPER", "BUHLER", "JOPER",
];

// ── ROASTER BASE MODELS (BASE 0.5 ~ 20, image map from reference) ──
export const ROASTER_BASE_MODELS = [
  {
    id: "base-05",
    name: "BASE 0.5",
    code: "KBN1000-M-05",
    capacity: "0.5kg",
    target: "Sample / Education",
    targetKr: "샘플 로스팅 / 교육용",
    size: "56 × 89 × 92cm",
    weight: "65kg",
    power: "0.72kW",
    burner: "5kW",
    controller: "Manual / Digital Speed",
    image: `${S3_PRODUCT}/roaster-05kg-1.jpg`,
    gallery: [
      `${S3_PRODUCT}/roaster-05kg-1.jpg`,
      `${S3_PRODUCT}/roaster-05kg-2.jpg`,
      `${S3_PRODUCT}/roaster-05kg-3.jpg`,
      `${S3_PRODUCT}/roaster-05kg-4.jpg`,
    ],
  },
  {
    id: "base-1.5",
    name: "BASE 1.5",
    code: "KBN1000-M-1.5",
    capacity: "1.5kg",
    target: "Small Café / Education",
    targetKr: "소형 카페 / 교육기관",
    size: "87 × 115 × 127cm",
    weight: "155kg",
    power: "1.84kW",
    burner: "10kW",
    controller: "PLC (optional)",
    image: `${S3_PRODUCT}/roaster-1_5kg-1.jpg`,
    gallery: [
      `${S3_PRODUCT}/roaster-1_5kg-1.jpg`,
      `${S3_PRODUCT}/roaster-1_5kg-2.jpg`,
      `${S3_PRODUCT}/roaster-1_5kg-3.png`,
      `${S3_PRODUCT}/roaster-1_5kg-4.png`,
      `${S3_PRODUCT}/roaster-1_5kg-5.png`,
    ],
  },
  {
    id: "base-3",
    name: "BASE 3",
    code: "KBN1000-M-3",
    capacity: "3kg",
    target: "Roastery Café",
    targetKr: "로스터리 카페",
    size: "87 × 135 × 150cm",
    weight: "270kg",
    power: "1.24kW",
    burner: "27.5kW",
    controller: "PLC (optional)",
    image: `${S3_PRODUCT}/roaster-3kg-1.jpg`,
    gallery: [
      `${S3_PRODUCT}/roaster-3kg-1.jpg`,
      `${S3_PRODUCT}/roaster-3kg-2.jpg`,
      `${S3_PRODUCT}/roaster-3kg-3.png`,
      `${S3_PRODUCT}/roaster-3kg-4.png`,
      `${S3_PRODUCT}/roaster-3kg-5.png`,
    ],
  },
  {
    id: "base-5",
    name: "BASE 5",
    code: "KBN1000-M-5",
    capacity: "5kg",
    target: "Medium Roastery",
    targetKr: "중형 로스터리",
    size: "90 × 155 × 165cm",
    weight: "330kg",
    power: "1.84kW",
    burner: "35kW",
    controller: "Software & Touchscreen",
    image: `${S3_PRODUCT}/roaster-5kg-1.jpg`,
    gallery: [
      `${S3_PRODUCT}/roaster-5kg-1.jpg`,
      `${S3_PRODUCT}/roaster-5kg-2.jpg`,
      `${S3_PRODUCT}/roaster-5kg-3.png`,
      `${S3_PRODUCT}/roaster-5kg-4.png`,
      `${S3_PRODUCT}/roaster-5kg-5.png`,
    ],
  },
  {
    id: "base-10",
    name: "BASE 10",
    code: "KBN1000-M-10",
    capacity: "10kg",
    target: "Large Roastery",
    targetKr: "대형 로스터리 카페",
    size: "107 × 195 × 190cm",
    weight: "480kg",
    power: "2.24kW",
    burner: "55kW",
    controller: "Full Auto / Touchscreen",
    image: `${S3_PRODUCT}/roaster-10kg-1.jpg`,
    gallery: [
      `${S3_PRODUCT}/roaster-10kg-1.jpg`,
      `${S3_PRODUCT}/roaster-10kg-2.jpg`,
      `${S3_PRODUCT}/roaster-10kg-3.png`,
      `${S3_PRODUCT}/roaster-10kg-4.png`,
    ],
  },
  {
    id: "base-15",
    name: "BASE 15",
    code: "KBN1000-M-15",
    capacity: "15kg",
    target: "Large Factory",
    targetKr: "대형 로스팅 공장",
    size: "107 × 200 × 195cm",
    weight: "530kg",
    power: "2.24kW",
    burner: "55kW",
    controller: "Software & Touchscreen",
    image: `${S3_PRODUCT}/roaster-15kg-1.png`,
    gallery: [
      `${S3_PRODUCT}/roaster-15kg-1.png`,
      `${S3_PRODUCT}/roaster-15kg-2.png`,
      `${S3_PRODUCT}/roaster-15kg-3.png`,
      `${S3_PRODUCT}/roaster-15kg-4.jpg`,
    ],
  },
  {
    id: "base-20",
    name: "BASE 20",
    code: "KBN1000-M-20",
    capacity: "20kg",
    target: "Industrial",
    targetKr: "산업용 로스팅",
    size: "115 × 210 × 205cm",
    weight: "670kg",
    power: "2.24kW",
    burner: "35kW",
    controller: "Software & Touchscreen",
    image: `${S3_PRODUCT}/roaster-20kg-1.jpg`,
    gallery: [
      `${S3_PRODUCT}/roaster-20kg-1.jpg`,
      `${S3_PRODUCT}/roaster-20kg-2.jpg`,
      `${S3_PRODUCT}/roaster-20kg-3.jpg`,
      `${S3_PRODUCT}/roaster-20kg-4.jpg`,
    ],
  },
];

export const ROASTER_SUPREME_IMAGE = `${S3_PRODUCT}/roaster-supreme-1.png`;
export const ROASTER_SUPREME_GALLERY = [
  `${S3_PRODUCT}/roaster-supreme-1.png`,
  `${S3_PRODUCT}/roaster-supreme-2.jpg`,
  `${S3_PRODUCT}/roaster-supreme-3.jpg`,
  `${S3_PRODUCT}/roaster-supreme-4.jpg`,
  `${S3_PRODUCT}/roaster-supreme-5.png`,
];

// ── NUT BUTTER MACHINE · NUTS-STAR (real spec from reference) ──
export const NUTBUTTER_PRODUCT = {
  id: "nuts-star",
  nameEn: "Nut Butter Machine · NUTS-STAR",
  nameKr: "넛버터 머신 · 넛츠스타",
  tagline: "갓 만든 신선함을 경험하세요",
  image: `${S3_PRODUCT}/nutbutter-main.png`,
  heroImage: `${S3_PRODUCT}/hero-nutbutter.png`,
  gallery: [
    `${S3_PRODUCT}/nutbutter-main.png`,
    `${S3_PRODUCT}/hero-nutbutter.png`,
  ],
  features: [
    "다양한 견과 호환 (땅콩, 아몬드, 캐슈넛, 호두 등)",
    "국내제조 특허기술 (KC인증, 국내 자체 생산)",
    "손쉬운 질감 조절 (SMOOTH ~ CRUNCHY)",
    "간편한 원터치 조작 (ON/OFF 일체형 버튼)",
    "고성능 인버터 제어 (1.5kW 고효율 모터)",
    "위생적 스테인리스 스틸 (STS304 하우징 적용)",
    "가정용 220V 전원 사용",
    "컴팩트한 소형 크기 (카운터 설치 가능)",
  ],
  specs: [
    { label: "MODEL", value: "NUTS-STAR · 넛츠스타" },
    { label: "THROUGHPUT", value: "50 kg / hour" },
    { label: "POWER", value: "220V · 50 / 60 Hz" },
    { label: "DRIVE", value: "1.7 kW inverter control" },
    { label: "DIMENSIONS", value: "254 × 600 × 680 mm (W×L×H)" },
    { label: "WEIGHT", value: "35 kg" },
    { label: "HOUSING", value: "Stainless Steel · STS304" },
    { label: "SAFETY", value: "E-Stop · Overload · Ground · Insulation" },
    { label: "CERTIFICATION", value: "KC 전기용품 안전인증" },
  ],
  applications: ["CAFÉ", "BAKERY", "HOTEL", "RESTAURANT", "SPECIALTY FOOD", "MILL HOUSE"],
  applicationsKr: "카페 · 베이커리 · 호텔 · 레스토랑 · 견과류 매장 · 방앗간",
};

export const HERO_IMAGES = {
  afterburner: `${S3_PRODUCT}/hero-afterburner.png`,
  roaster: `${S3_PRODUCT}/hero-roaster.png`,
  nutbutter: `${S3_PRODUCT}/hero-nutbutter.png`,
};
